WasatchPhotonics/Wasatch.PY

README_CHANGELOG.md
WasatchShell/wasatch-shell.py
demo.py
wasatch/AndorDevice.py
wasatch/BLEDevice.py
wasatch/FeatureIdentificationDevice.py
wasatch/InterfaceDevice.py
wasatch/MockUSBDevice.py
wasatch/OceanDevice.py
wasatch/SpectrometerRequest.py
wasatch/SpectrometerResponse.py
wasatch/SpectrometerState.py
wasatch/WasatchDevice.py
wasatch/WasatchDeviceWrapper.py
wasatch/WrapperWorker.py
wasatch/__init__.py
wasatch/utils.py

Lots of changes here. The structure I messaged you about is repeated in the doc string for the different interface classes. I've tested the changes with Andor, Wasatch, and BLE and general features of gain, int, batch collection, are working from my testing that I've done. In general there was also some of my attempts at adding newer python features to the code such as adding type hints to the various interface files.

Corrupt eeprom handling

---

wasatch/BLEDevice.py
wasatch/InterfaceDevice.py
wasatch/SpectrometerResponse.py
wasatch/WasatchDeviceWrapper.py
wasatch/WrapperWorker.py

This includes the nonBlockSettings PR

Ble load bars

---

Makefile
README_PYPI.md
demo-workflow.py
wasatch/FeatureIdentificationDevice.py

- added workflow demo
- disable laser by on connection
- enable TEC on connection
I thought Wasatch.PY (and all our drivers) automatically disabled the laser and enabled the TEC upon successful connection.  I'm not sure if that got accidentally removed at some point, or if this caused a problem with new features for Ocean, Andor, Mocks etc?

added demo-workflow.py; some new docs

---

Makefile
README.md
README_CHANGELOG.md
README_PYPI.md
wasatch/FeatureIdentificationDevice.py
wasatch/__init__.py

- wasatch-shell.py was giving warnings about has_linearity_coeffs (function had been renamed)
- updated some docs as I did some testing with PyPi

Docs and bugfix while testing PyPi

---

README_CHANGELOG.md
wasatch/BLEDevice.py
wasatch/WasatchDevice.py
wasatch/WrapperWorker.py
wasatch/__init__.py

This started as a focus on cleaning up all the if elif statement for each new device type. This makes it cleaner for when we continue to add more device types. It turned into finding the fix for why BLE wasnt working and includes those changes.

Device refactor

---

README_CHANGELOG.md
wasatch/AndorDevice.py
wasatch/DeviceID.py
wasatch/EEPROM.py
wasatch/FeatureIdentificationDevice.py
wasatch/SpectrometerResponse.py
wasatch/WasatchDeviceWrapper.py
wasatch/__init__.py
wasatch/utils.py

- Andor updates
- search for DLL in various locations
- support startup\_integration\_time\_ms and startup\_temp\_degC in JSON 
- default startup\_temp\_degC to -55C if not specified in JSON
- added DeviceID.is_andor()
- populate SpectrometerState.shutter_enable
- respect array length in EEPROM.generate\_write\_buffers

Mzieg andor testing

---

wasatch/MockUSBDevice.py
wasatch/WasatchDevice.py

Tested with the pytest .\test folder and all passed when combined with the updates on bitbucket

fix typo that broke change_setting, fix MUD

---

README_CHANGELOG.md
wasatch/AndorDevice.py
wasatch/WrapperWorker.py
wasatch/__init__.py

changes for DU940P-BU

---

README_CHANGELOG.md
wasatch/FeatureIdentificationDevice.py
wasatch/WasatchDevice.py
wasatch/__init__.py

Populate laser attributes on Readings.  Also rolled-up process_f assignments to avoid opportunity for typos.

Laser interlock monitoring

---

README_CHANGELOG.md
wasatch/AndorDevice.py
wasatch/CSVLoader.py
wasatch/FPGAOptions.py
wasatch/RealUSBDevice.py
wasatch/__init__.py

pass-in CSV encoding (default utf-8)

CSVLoader: support specified encoding

---

README_CHANGELOG.md
wasatch/AndorDevice.py
wasatch/__init__.py

needs testing since I don't have an andor unit.

andor high gain

---

WasatchShell/wasatch-shell.py

Creating the PR now so it is ready. Dark has been tested but still waiting on srm unit.

Shell dark srm

---

README.md
README_CHANGELOG.md
WasatchShell/wasatch-shell.py
wasatch/AndorDevice.py
wasatch/CommandSettings.py
wasatch/DetectorROI.py
wasatch/DetectorRegions.py
wasatch/EEPROM.py
wasatch/FeatureIdentificationDevice.py
wasatch/InterfaceDevice.py
wasatch/ROI.py
wasatch/SPIDevice.py
wasatch/SpectrometerSettings.py
wasatch/WasatchDevice.py
wasatch/WasatchDeviceWrapper.py
wasatch/__init__.py

* imported functions from updated spi_console.py
* stop "searching" for start bytes in SPI stream
* populate and validate CRC
* support 24-bit integration time
* support floating-point gain
* support high-speed readout with configurable block size

SPI updates

---

README_CHANGELOG.md
wasatch/SpectrometerSettings.py
wasatch/__init__.py

Accidentally fixed Kevin's issue while trying to replicate it

[2.1.15] bugfix for spectra loaded from file

---

wasatch/BLEDevice.py
wasatch/DeviceFinderUSB.py
wasatch/DeviceID.py
wasatch/FeatureIdentificationDevice.py
wasatch/SpectrometerSettings.py
wasatch/WasatchBus.py
wasatch/WasatchDevice.py
wasatch/WrapperWorker.py

Hi Evan,
This is not a cohesive set of known-good changes.  This is a set of tweaks I made over a span of several days while testing different types of spectrometers, with different goals.  I'm not sure all the changes are necessarily good ideas, or required for success.
HOWEVER, I definitely have more success with a simple WP-785 unit, turning the spectrometer's power on and off repeatedly, and having ENLIGHTEN automatically and successfully reconnect each time, than with our current baseline on main.
Therefore, I think this changeset does more good than harm...but it honestly needs a second pair of eyes, and would benefit some some hard questions "Why did you do this?" if something doesn't make sense.

Mzieg testing devicefinder

---

README_CHANGELOG.md
wasatch/BLEDevice.py
wasatch/DeviceID.py
wasatch/FeatureIdentificationDevice.py
wasatch/WasatchDevice.py
wasatch/WasatchDeviceWrapper.py
wasatch/WrapperWorker.py
wasatch/__init__.py

Restructures device creation so that BLE is created from the Device ID and DeviceID class no longer carries the entire BLE class.

Device ID refactor

---

README_CHANGELOG.md
wasatch/WasatchDevice.py
wasatch/__init__.py

Adding here since pr is present for ENLIGHTEN

Ext trigger fix

---

wasatch/utils.py

bugfix in RamanShiftCorrection

avoid floating-point array index lookup

---

demo-virtual.py
wasatch/FeatureIdentificationDevice.py
wasatch/MockUSBDevice.py
wasatch/WasatchDevice.py
wasatch/WasatchDeviceWrapper.py
wasatch/WrapperWorker.py

Discussion in ENLIGHTEN pull request

Trying to get pytest working

---

README_CHANGELOG.md
wasatch/FeatureIdentificationDevice.py
wasatch/__init__.py

[2.1.25] disable laserEnable verification for XS

---

demo-simple.py
requirements.txt

Added pipy compatible requirements. Demo missing dependency

Small improvements

---

README_CHANGELOG.md
WasatchShell/wasatch-shell.py
demo-workflow.py
wasatch/AndorDevice.py
wasatch/BLEDevice.py
wasatch/DetectorRegions.py
wasatch/DeviceFinderUSB.py
wasatch/DeviceID.py
wasatch/EEPROM.py
wasatch/FeatureIdentificationDevice.py
wasatch/HardwareInfo.py
wasatch/InterfaceDevice.py
wasatch/MockUSBDevice.py
wasatch/OceanDevice.py
wasatch/ProcessedReading.py
wasatch/SPIDevice.py
wasatch/SpectrometerSettings.py
wasatch/WasatchBus.py
wasatch/WasatchDevice.py
wasatch/WasatchDeviceWrapper.py
wasatch/WrapperWorker.py
wasatch/utils.py

I don't like adding weight to obvious 1-line convenience accessors but different methods following the same naming style are returning different types.

is_striving_for_api_consistency

---

README_CHANGELOG.md
wasatch/ProcessedReading.py
wasatch/SpectrometerSettings.py

[W] 0 Renaming vignette -> crop

---

WasatchShell/wasatch-shell.py
wasatch/FeatureIdentificationDevice.py

- fixed offset gettors not returning SpectrometerResponse
- improved WasatchShell handling of SpectrometerResponse

WasatchShell updates

---

tests/existing_implementations.py
tests/unit.py
wasatch/utils.py

Test results
```
==================================================================================================
Comparing utils.apply_boxcar with known implementation.
--------------------------------------------------------------------------------------------------
Sim spectra with half_width=5
99.22% (1016 entries) is an exact match.
0.20% (2 entries) does not match but is within 5%.
0.59% (6 entries) is more than 5% different.
Error factor: 5.68
--------------------------------------------------------------------------------------------------
Sim spectra with half_width=20
96.29% (986 entries) is an exact match.
0.29% (3 entries) does not match but is within 5%.
3.42% (35 entries) is more than 5% different.
Error factor: 16.03 …
```

Sbee boxcar fringe

---

wasatch/DeviceFinderUSB.py

Related to https://github.com/WasatchPhotonics/ENLIGHTEN/pull/273

Macs can use libusb-1.0

---

CHANGELOG.md
wasatch/FeatureIdentificationDevice.py
wasatch/__init__.py

force laser to disable on %/PWM zero

---

CHANGELOG.md
demo.py
wasatch/WasatchDeviceWrapper.py
wasatch/WrapperWorker.py
wasatch/__init__.py

- update demo.py to support multiple spectrometers
- give WrapperWorker an optional callback for IoC

[#102] update demo.py to support multiple spectrometers

---

CHANGELOG.md
wasatch/AutoRaman.py
wasatch/AutoRamanRequest.py
wasatch/BLEDevice.py
wasatch/FeatureIdentificationDevice.py
wasatch/SpectrometerResponse.py
wasatch/SpectrometerState.py
wasatch/WasatchDeviceWrapper.py
wasatch/__init__.py

- ensure all queued messages are flowed upstream
- AutoRaman
- output progress bar updates
- support configurable Laser Warning Delay
- averaging bugfix
- trying to support non-zero initial gain dB

AutoRaman fixes

---

CHANGELOG.md
wasatch/EEPROM.py
wasatch/__init__.py

Relates to https://github.com/WasatchPhotonics/ENLIGHTEN/pull/482

added disableLaserArmedIndicator and blePowerEnabled

---

CHANGELOG.md
wasatch/FeatureIdentificationDevice.py
wasatch/FirmwareRequirements.py

add firmware version checks around new features

---

CHANGELOG.md
wasatch/EEPROM.py
wasatch/FeatureIdentificationDevice.py
wasatch/__init__.py

prefer new startup laser TEC setpoint EEPROM field

---

CHANGELOG.md
wasatch/FeatureIdentificationDevice.py
wasatch/SpectrometerSettings.py
wasatch/__init__.py

Add Linear Pixel Calibration
